apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
    #namespace: evershop
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/postgres"

