apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evershop-ingress
  namespace: {{ .Values.appConfig.namespace }}
spec:
  rules:
  - host: evershop.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: evershop-service
            port:
              number: 80
