apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: {{ .Values.metalLbConfig.namespace }}
spec:
  addresses:
    - {{ .Values.metalLbConfig.addressRange }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: {{ .Values.metalLbConfig.namespace }}
spec:
  ipAddressPools:
  - first-pool
  interfaces:
  - {{ .Values.metalLbConfig.interface }}
