apiVersion: v1
kind: PersistentVolume
metadata:
  name: repo-pv
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "60"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/repo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-pvc
  namespace: {{ .Values.appConfig.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "70"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual